version: "3"
services:
  gostack_desafio06:
    container_name: gostack_desafio06
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  gostack_desafio06-admin:
    container_name: gostack_desafio06-admin
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: gobarber@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: docker
    ports:
      - "5050:80"
    depends_on:
      - gostack_desafio06
